[package]
name = "hyperspeed-webrtc"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# actix-web = "3.3.2"

mediasoup = "0.8.2"

futures = "0.3.15"
async-std = { version = "1.8.0", features = ["attributes", "unstable"] }
async-tungstenite = { version = "0.14.0", features = ["tokio-runtime"] }

# serde
serde_json = "1.0.64"
serde = { version = "1.0.126", features = ["derive"] }

# WebRTC
rtp = "0.2.9"
bytes = "1.0.1"
webrtc-util = "0.2.4"
# webrtc = { git = "https://github.com/webrtc-rs/webrtc" }
